# Generated by Django 4.2.2 on 2023-08-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default='https://placehold.co/400', null=True, upload_to='media'),
        ),
    ]
